# Generated by Django 3.2.3 on 2021-06-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_productcategory_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='href',
            field=models.URLField(verbose_name='url'),
        ),
    ]
