# Generated by Django 3.2.3 on 2021-06-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_merge_20210611_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
