# Generated by Django 3.2.3 on 2021-06-11 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_productcategory_updated'),
        ('mainapp', '0007_remove_productcategory_href'),
    ]

    operations = [
    ]
